version: '3.9'

services:

  app:
    build: .
    container_name: app
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  db:
    image: postgres
    container_name: genesis_academy_postgres
    restart: always
    ports:
      - 5432:5432
    shm_size: 128mb # Set shared memory limit. Image docs recomendation - do not remove
    environment:
      POSTGRES_DB: genesis_acad_db
      POSTGRES_USER: genesis_user
      POSTGRES_PASSWORD: verysecretpass